spring:
  application:
    name: yeguoAPI-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api
    username: root
    password: 123456
  # session
  session:
    timeout: 86400
    store-type: redis
    redis:
      namespace: yeguo:session
  # redis
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
# server
server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: icu.yeguo.yeguoapi.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-provider
  protocol:
    name: dubbo
  #    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
pay:
  address:
  notify:
    url:
  return:
    url:
  site:
    name:
  sign:
    type:
  pid:
  key:
