autoDetectedPackages:
- icu.yeguo.apicommon.constant
- icu.yeguo.apicommon.model.entity
- icu.yeguo.apicommon.service
- icu.yeguo.apigateway
- icu.yeguo.yeguoapi
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
startOnDebug: false
