spring:
  application:
    name:
      API_gataway
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=source, yeguo_api_gateway # 流量染色
      routes:
        - id: api_router
          uri: http://localhost:8082
          predicates:
            - Path=/api/app/**
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  datasource:
    data:
      redis:
        port: 6379
        host: 127.0.0.1
        database: 0
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
server:
  port: 8081

dubbo:
  application:
    enable-file-cache: false
    qosEnable: false
    name: dubbo-springboot-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

yeguo:
  gateway:
    base-url: http://localhost:8081

